### ISSUE TITLE
fazer o texto da home do site

### ISSUE THREAD

**Issue by avorio** [avorio/paraentender#49]
1) 

Seja bem-vindo ao Para Entender a Internet, um livro vivo que se atualiza e no qual você pode participar como autor. Conheça a história e o conceito deste projeto.

história http://paraentender.com/entenda/sobre
conceito http://paraentender.com/entenda/conceito

BLURB AO LADO DA CAPA DO LIVRO

Baixe o PDF grátis.

Compre o livro impresso pelo Clube de Autores - http://goo.gl/kB7vJH

Compre o ebook nas lojas a seguir:

AMAZON.COM.BR http://goo.gl/lrajFm

GOOGLE PLAY https://goo.gl/4HijvS

LIVRARIA CULTURA http://goo.gl/KfhEL4

KOBO http://goo.gl/KfhEL4

2) lista das 3 áreas

3) Envie um texto

O Para Entender é um livro em constante processo de transformação. Se existe um tópico relacionado à temática da internet que não tenha sido contemplado, se torne o autor desse texto. 

Para ser adicionado à próxima edição, seu texto deve estar aprovado até 25 de janeiro de 2016.

Estes são alguns temas a procura de autores:

- Antropologia digital
- WhatsApp
- Livro eletrônico
- Dark Web
- Anonymous
- Pornografia online

Existem ainda [outras formas] de participar. http://paraentender.com/entenda

**Comment by avorio** [comment]
- [ ] criar o blurb que aparece ao lado da imagem da capa do livro
- [ ] incluir os links para cada item (pdf, epub, etc.)

**Comment by jspyer** [comment]
aqui tem o link explicando como conseguir o link pro itunes
http://www.apple.com/itunes/marketing-your-books-on-ibooks/marketing-guidelines.html#ibooks-badge

**Comment by jspyer** [comment]
confirmacao final - estes sao os links de compra

Amazon: http://www.amazon.com.br/Para-Entender-Internet-Andr%C3%A9-Avorio-ebook/dp/B010TBP94Q/ref=sr_1_1?ie=UTF8&qid=1439302706&sr=8-1&keywords=para+entender+a+internet

KOBO: https://store.kobobooks.com/pt-BR/ebook/para-entender-a-internet

Livraria Cultura: http://www.livrariacultura.com.br/p/para-entender-a-internet-91318860

Google: https://play.google.com/store/books/details/Andr%C3%A9_Avorio_Para_Entender_A_Internet?id=cwISCgAAQBAJ

Apple: https://itunes.apple.com/br/book/para-entender-a-internet/id1026892200?mt=11

Saraiva: http://www.saraiva.com.br/para-entender-a-internet-8905976.html

**Comment by jspyer** [comment]
wook nao esta disponivel

**Comment by jspyer** [comment]
No link de compra para o livro impresso, informar que a entrega eh so no Brasil.

**Comment by avorio** [comment]
vários dos links acima não estão mais funcionando.

aqui estão os que funcionam agora:

http://www.saraiva.com.br/para-entender-a-internet-8905976.html
https://play.google.com/store/books/details/André_Avorio_Para_Entender_A_Internet?id=cwISCgAAQBAJ
http://www.livrariacultura.com.br/p/para-entender-a-internet-101528612
https://store.kobobooks.com/pt-br/ebook/para-entender-a-internet-1
https://www.amazon.com.br/Entender-Internet-André-Avorio-Juliano-ebook/dp/B019HU4T3C/ref=sr_1_1?ie=UTF8&qid=1463942246&sr=8-1&keywords=para+entender+a+internet

**Comment by avorio** [comment]
FEITO! http://paraentender.com/
