### ISSUE TITLE
Resposta ao Ricardo A. (Clube de Autores)

### ISSUE THREAD

**Issue by jspyer** [avorio/paraentender#56]
- [x] passar o arquivo mais recente
- [x] passar capa
- [x] perguntar se ajuda com sumário do epub que nao clica no titulo
- [x] perguntar se cada volume precisará de isbn novo
- [x] perguntar qual data recomenda, quanto tempo até o lançamento e ver se nao vale a pena lançar sem isbn porque só conta para saraiva
- [x] confirmar que digital será grátis
- [x] checar custo do exemplar impresso
- [x] checar se vao entregar em livrarias
- [x] pedir o plano de lançamento
- [x] devo circular o nosso livro entre algumas pessoas para pegar áspas?
- [x] nosso designer está fazendo a orelha e contracapa nas dimensoes pedidas
- [x] andré informa ao clube (ricardo e paulo) quanto tempo precisará para concluir a capa depois que receber os textos do juliano

**Comment by avorio** [comment]
3 fins de semana lead time.
