### ISSUE TITLE
aspas de recomendação do livro

### ISSUE THREAD

**Issue by jspyer** [avorio/paraentender#70]
pensei em usar esse material para fazer a primeira capa do site. o que acha?

**Comment by avorio** [comment]
@jspyer as aspas, please?

**Comment by jspyer** [comment]
Áspas para lançamento Para Entender, 2a edição

"O projeto me lembra a coleção Primeiros Passos, que tratava de assuntos mundanos e complexos, mas que sempre disfarçava a complexidade do assunto em edições pequenas, de bolso, quase inofensivas. Quando o objetivo é 'Entender a Internet', o ideal é que seja feito como esta coleção, com textos pequenos escritos por alguns dos maiores especialistas do mercado brasileiro, mas acima de tudo fáceis de ler. Ao final, dá pra entender a Internet? Lógico, exceto que ela continua mudando. E a gente também, como tudo. Mas a vontade de entender permanece com o leitor."
>> Eduardo Acquarone, editor executivo de mídias digitais da TV Globo e bolsista do Tow Knight Center em Nova York

"A riqueza dos textos no 'Para Entender', e seu processo participativo de produção, tanto revelam uma necessidade de perdermos a visão ingênua de que compreendemos a Internet somente a partir do nosso uso, popularizada no mito dos 'nativos digitais', como demonstram a capacidade de adaptação dessa sociedade em rede, abrindo caminhos para juntos aprofundarmos nosso pensamento!"
>> Ale Abdo, membro do Garoa Hacker Clube

"Não existe dúvida de que a computação e a Internet são as forças transformadores mais fortes que a humanidade conheceu nas últimas quatro décadas e que, provavelmente, continuarão assim pelas próximas quatro. Entender os conceitos e dinâmicas que fazem da Internet este motor de transformação e suas principais conseqüências e implicações para o indivíduo, a sociedade e os negócios é fundamental para vivermos melhor neste mundo conectado. Este livro foi construído sobre os fundamentos da rede e é um guia para nós, os usuários."
>> Manoel Lemos, Sócio da Redpoint e.Ventures e Fundador do Fazedores.Com

"O Para Entender a Internet traz uma visão privilegiada de como a tecnologia e a comunicação se organizaram em rede, o livro é escrito por diversas pessoas que experimentaram esses conceitos na prática, muitas vezes antes deles se tornarem padrões de mercado e em alguns casos os autores aqui presentes ajudaram na própria criação ou consolidação desse conceito. É uma visão de dentro sem exageros ou tecnicismos, o livro é escrito numa linguagem acessível para quem quer se familiarizar com as tecnologias a serviços da comunicação do mundo atual e se libertar dos conceitos ultrapassados do século XX."
>> Edney Souza, Professor da ESPM e FGV e Consultor independente

"O Para Entender a Internet foi uma iniciativa importante para fomentar a inclusão digital no Brasil. Ver o projeto ganhar as prateleiras é um misto de orgulho com sentimento de dever cumprido."
>> Rafael Ziggy, Estrategista Digital da Agência Africa

"O Para Entender traz textos fáceis de ler e que agradam desde novatos até quem já trabalha na área, pois são tantos os temas abordados que sempre tem alguma novidade até pros experts. Agora que o projeto virtual chega ao papel cabe a todos nós fazemos o que já fazemos online, não deixar o livro parado numa estante e circulá-lo entre amigos, parentes e desconhecidos"
Carlos Estigarribia, sócio da RightZero e fundador da ABRAGAMES e da NearBytes

"O Para Entender a Internet nunca foi tão atual. Os temas exigem um olhar e reflexão ainda mais cuidadoso por parte dos consumidores e das empresas. E continuarão sendo uma preocupação constante das próximas gerações que trabalham com Comunicação Digital."
>> Alessandro Lima, CEO da E.life 

"Seis anos se passaram do lançamento original do 'Para Entender...' e eis o livro aqui: não só ainda pertinente, mas também crescido e fortalecido. Isso é uma boa medida do quanto os artigos conseguiram de fato tocar no cerne dos seus temas e do quanto os organizadores foram bem sucedidos na seleção do que deveria ser abordado, mas é sobretudo uma amostra de que o livro é, em si mesmo, um exemplo de uma prática de produção cultural típica da internet."
Diego Franco, pesquisador e professor da Universidade Metodista de SP

"Quem pode dizer que entende completamente a tal de Internet, essa jovem senhora tão cheia de caprichos e de personalidade forte e mutante? Quando a gente acha que já a domina ela se transmuta e nos deixa com jeitão de dinossauros pelo caminho. É desse jeito. Mulheres... pelo menos essa, agora, tem manual - o 'Para entender a Internet'."  
Wagner Fontoura, CEO da Coworkers Full Digital

"Entender a Internet é um BHAG como diz Jim Collins em Built to Last, um Big Hairy Audicious Goal, um objetivo enorme, audacioso e cabeludo! E assim, os desorganizadores dessa empreitada reuniram pessoas dos mais diferentes campos de atuação. Acadêmicos, ativistas políticos, profissionais, executivos, todos trabalhando em conjunto contribuindo e colaborando para esse enorme objetivo. Espero que gostem do livro e que entendam que sozinhos nenhum de nós entende a Internet."
>> Stelleo Tolda, COO do MercadoLivre

"Para alguns a Internet parece uma coisa óbvia. Para os mais jovens, que já nasceram conectados na Web, isso é ainda mais verdadeiro. O que este livro mostra é que não é bem assim. Essa rede de computadores espalhados pelo mundo utilizou, na sua formação, e mobilizou, no seu desenvolvimento, uma série de conceitos, ideias e comportamentos que a transformaram em uma instituição, no sentido sociológico do termo. A Internet enquanto instituição não é uma coisa óbvia e esse livron os ajuda a entende-la de modo diferente e melhor."
>> Fernando Guarnieri é professor de Ciência Política do IESP/UERJ

"Em tempos de ubiquidade total de dispositivos, onde as telas ultrapassaram o status de interface para se fundir aos seres humanos numa simbiose de dados e emoções, Para Entender a Internet ainda é o melhor manual de instruções para novatos e veteranos no ambiente digital. Tudo o que você precisa saber para navegar com segurança na web está nesse guia. Mergulhe sem medo."
>> Fábio Fernandes, escritor, tradutor, pesquisador e professor da PUC-SP

**Comment by jspyer** [comment]
manfredo, voce vai precisar disso ainda ou podemos fechar a ocorrencia?

**Comment by avorio** [comment]
ainda não implementei essas aspas no site, então deixe aberto, please.

colocamos todas na capa ou uma seleção delas?

**Comment by jspyer** [comment]
tem jeito de ficar em rotacao? aparece uma ou duas aleatoriamente em cada
acesso? (quero dizer, é obvio que tem jeito, mas é facil, rapido, inodor,
etc?)

**Comment by avorio** [comment]
- [ ] criar botão "por que ler" no menu de navegação principal
- [ ] adicionar seleção de aspas na capa embaixo da seção de "call for papers"

**Comment by avorio** [comment]
Solução temporária para quotes implementada.

Ficaram faltando avatars de Diego Franco e Ale Abdo. Alguma ideia de qual imagem podemos usar?

**Comment by jspyer** [comment]
manfre - aqui vao os links pros perfis deles na plataforma lattes, de pesquisadores brasileiros:

abdo - http://www.bv.fapesp.br/pt/pesquisador/63524/alexandre-hannud-abdo/

franco - http://lattes.cnpq.br/8805392779597281

**Comment by avorio** [comment]
Feito!
