### ISSUE TITLE
CMS nao tira do ar autores com textos em rascunho

### ISSUE THREAD

**Issue by jspyer** [avorio/paraentender#75]
a gabriela dias pediu para o texto dela ser excluido da coletanea porque está desatualizado. eu alterei o status para rascunho e destiquei o item "published" em publishing options. 

o texto ja nao consta na lista de conteudo, mas a autora continua aparecendo na lista de autores.

**Comment by avorio** [comment]
oi @jspyer

o site usa cache para otimizar o tempo de carregamento das páginas. isso quer dizer que algumas mudanças no banco de dados não aparecem imediatamente no site. como essa, por exemplo, de tirar um artigo do ar. em geral, a mudança acontece dentro de 3 horas.

nesse caso, imagino que você tenha checado a lista de autores imediatamente depois de alterar as configurações do texto da Gabriela Dias. acabei de checar agora e o nome dela não consta mais na lista de autores, como esperado.

assim, tô marcando essa issue como resolvida.
