### ISSUE TITLE
Upload final e-book files to the server

### ISSUE THREAD

**Issue by avorio** [avorio/paraentender#8]
Mandei o arquivo por email. 

A capa continua desproporcionalmente grande em relaçao ao restante do livro, mas esse arquivo funcionará agora para termos o site pronto. Quando houver tempo, vou conseguir ajuda pra editar esse arquivo e o atualizamos no servidor.

**Comment by avorio** [comment]
waiting on files from Juca

**Comment by avorio** [comment]
@jspyer Onde está o PDF final, please?

**Comment by jspyer** [comment]
o joao parece ter interrompido a troca de emails pra resolver o tamanho da desproporcao entre capa grande e miolo pequeno no formato pdf.

**Comment by jspyer** [comment]
resolvido. tenho o arquivo com capa e corpo do texto do mesmo tamanho
